### ISSUE TITLE
Deliver ROR ID to DataCite via Metadata Schema

### ISSUE THREAD

**Issue by yvgrossmann** [MPDL/dataverse#43]
**Current status**: Currently, no ROR IDs of datasets are supplied to DataCite. Therefore, no datasets from Edmond currently appear in the DataCite Commons: https://commons.datacite.org/ror.org/01hhn8329?rorid=01hhn8329&resource-type=dataset. 

**Result:** It would be desirable, however, that the ROR IDs of datasets are delivered to DataCite. Then Edmond datasets would also appear in the DataCite Commons.

**Comment by haarli** [comment]
Currently, neither the 2nd or 3rd affilation, nor the ROR identifier of any affiliation is mapped  to the DataCite schema or any other export, as this was a custom enhancement on Dataverse.
see e.g. here: 
Dataset: https://edmond.mpdl.mpg.de/dataset.xhtml?persistentId=doi:10.17617/3.8w
Datacite Export: https://edmond.mpdl.mpg.de/api/datasets/export?exporter=Datacite&persistentId=doi:10.17617/3.8w
```xml
<creator>
<creatorName>Wei, David</creatorName>
<nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">https://orcid.org/0000-0002-7849-9935</nameIdentifier>
<affiliation>Max Planck Institute of Quantum Optics</affiliation>
</creator>
```
The DataCite Metadata schema supports affiliation identifiers since version 4.3: https://blog.datacite.org/identify-your-affiliation-with-metadata-schema-4-3/

In the export example above, a mapping including 2nd affiliation and ROR IDs should look like this:
```xml
<creator>
<creatorName>Wei, David</creatorName>
<nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">https://orcid.org/0000-0002-7849-9935</nameIdentifier>
<affiliation schemeURI="https://ror.org/" affiliationIdentifierScheme="ROR" affiliationIdentifier="https://ror.org/01vekys64">Max Planck Institute of Quantum Optics</affiliation>
<affiliation schemeURI="https://ror.org/" affiliationIdentifierScheme="ROR" affiliationIdentifier="https://ror.org/04xrcta15">Munich Center for Quantum Science and Technology</affiliation>
</creator>
```

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-1 (https://github.com/MPDL/dataverse/commit/3dce49cda89399e4bcdb173e40aa6e553c1db1eb)
User: Admin
Result: OK

All author affiliations (with ROR IDs) of a Dataset are now included in the Datacite Export and are send to Datacite during publication. As mentioned in https://github.com/MPDL/dataverse/issues/43#issuecomment-1204853713 this change only affects newly created Datasets (No update of existing published metadata).
