### ISSUE TITLE
ORCID autosuggest for authors

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#53]

**Comment by wilhelmfrank** [comment]
the 'auto suggest' queries the ORCID records via the ORCID search api.
it's not a real auto suggest, but matches search terms in the ORCID record.
i.e. starting to type 'grossmann' will return matches for 'gross' and later for 'grossman'.
to further limit the search results, you need to continue typing 'grossmann yves', in order to get results for Yves.
